apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: dual-pods
    app.kubernetes.io/component: controller
  name: "dual-pods-controller-in-{{ .Release.Namespace }}"
rules:
- apiGroups: [ "" ]
  resources: [ nodes ]
  verbs: [ get, list, watch ]
