apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}"
  labels:
    app.kubernetes.io/name: dual-pod
    app.kubernetes.io/component: controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: dual-pod
      app.kubernetes.io/component: controller
  template:
    metadata:
      labels:
        app.kubernetes.io/name: dual-pod
        app.kubernetes.io/component: controller
    spec:
      containers:
      - name: controller
        image: {{ .Values.Image }}
        command:
        - /app/controller
        - "-v=5"
        - "--namespace=$(POD_NAMESPACE)"
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
