apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: dual-pods
    app.kubernetes.io/component: controller
  name: dual-pods-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: dual-pods-controller
subjects:
- kind: ServiceAccount
  name: dual-pods-controller
